### ISSUE TITLE
I can't download the material of an episode

### ISSUE THREAD

**Issue by pedruchito** [raywenderlich/video-suif-materials#1]
Hi,

When I click on download material from a lesson instead of getting a zip file with all the files in it a GitHub window appear where I must select file by file what I wish. I used to do it with just a click and I could edit, compile my download project but I can't now. Any advice please, thank you very much.

here's an example,  https://github.com/raywenderlich/video-suif-materials/tree/versions/1.0/05-state-binding

**Comment by sammyd** [comment]
Hi @pedruchito 

When you go to the GitHub page, there is a green button on the right hand side called "code". If you click that, you can download a ZIP file of the entire course, which then works exactly the same way you're used to:

<img width="450" alt="image" src="https://user-images.githubusercontent.com/658798/105645955-f7c53780-5e94-11eb-8f9d-1ba7339d1e2f.png">

**Comment by pedruchito** [comment]
Thank you so much for answering and have a great and fabulous day 👏👍💪

Enviado desde mi ifofito
